# Generated by Django 4.2.11 on 2025-03-10 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_alter_client_options_remove_client_active_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='project',
            name='intent',
            field=models.TextField(blank=True, help_text='Description of project goals and intent for AI-assisted reporting', verbose_name='Project Intent'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_split_off',
            field=models.BooleanField(default=False, help_text='Whether this is a split-off project from a main project', verbose_name='Split-off Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='parent_project',
            field=models.ForeignKey(blank=True, help_text='The parent project if this is a split-off project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_projects', to='projects.project', verbose_name='Parent Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(help_text='The client this project belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the project was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='The date when the project ended or is expected to end', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='The name of the project', max_length=255, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the project', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text='The date when the project started', null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', help_text='Current status of the project', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the project was last updated', verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client', 'name'], name='projects_pr_client__249310_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'),
        ),
    ]
