# Generated by Django 4.2.11 on 2025-03-10 11:05

import apps.parsers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Device Type Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Device Type',
                'verbose_name_plural': 'Device Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.parsers.models.device_file_path, verbose_name='Configuration File')),
                ('name', models.CharField(max_length=255, verbose_name='Device Name')),
                ('parsed', models.BooleanField(default=False, verbose_name='Parsed')),
                ('parse_errors', models.TextField(blank=True, verbose_name='Parse Errors')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_files', to='parsers.devicetype', verbose_name='Device Type')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_files', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Device File',
                'verbose_name_plural': 'Device Files',
                'ordering': ['-created_at'],
            },
        ),
    ]
