# Generated by Django 4.2.11 on 2025-03-10 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name', '-created_at'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='active',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='client',
            name='industry',
            field=models.CharField(blank=True, help_text='The industry sector of the client', max_length=100, verbose_name='Industry'),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_contact_email',
            field=models.EmailField(blank=True, help_text='Email of the primary contact person', max_length=254, verbose_name='Primary Contact Email'),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_contact_name',
            field=models.CharField(blank=True, help_text='Name of the primary contact person', max_length=255, verbose_name='Primary Contact Name'),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_contact_phone',
            field=models.CharField(blank=True, help_text='Phone number of the primary contact person', max_length=20, verbose_name='Primary Contact Phone'),
        ),
        migrations.AddField(
            model_name='client',
            name='secondary_contact_email',
            field=models.EmailField(blank=True, help_text='Email of the secondary contact person', max_length=254, verbose_name='Secondary Contact Email'),
        ),
        migrations.AddField(
            model_name='client',
            name='secondary_contact_name',
            field=models.CharField(blank=True, help_text='Name of the secondary contact person', max_length=255, verbose_name='Secondary Contact Name'),
        ),
        migrations.AddField(
            model_name='client',
            name='secondary_contact_phone',
            field=models.CharField(blank=True, help_text='Phone number of the secondary contact person', max_length=20, verbose_name='Secondary Contact Phone'),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, help_text="Client's official website", verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the client was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='The name of the client organization', max_length=255, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the client', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the client was last updated', verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='clients_cli_name_5ab7bc_idx'),
        ),
    ]
