# Generated by Django 4.2.11 on 2025-03-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('cisco_ios', 'Cisco IOS'), ('cisco_asa', 'Cisco ASA'), ('cisco_nexus', 'Cisco Nexus'), ('fortigate', 'FortiGate'), ('fortiswitch', 'FortiSwitch'), ('junos', 'JunOS'), ('other', 'Other')], default='other', help_text='The platform/OS type of the device', max_length=20, verbose_name='Device Platform'),
        ),
    ]
