# Generated by Django 4.2.11 on 2025-03-11 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_update_device_type_field'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='device',
            new_name='inventory_d_device__4b4a89_idx',
            old_name='inventory_d_device__82f1fb_idx',
        ),
    ]
